### ISSUE TITLE
In thelounge v3.0-pre5 it doesn't correctly install sqlite

### ISSUE THREAD

**Issue by SinZ163** [thelounge/thelounge-deb#26]
```
Error: Cannot find module '/usr/lib/node_modules/thelounge/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/thelounge/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

Note `/usr/lib/node_modules/thelounge/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node` does exist, but not v59

**Comment by xPaw** [comment]
This is because whatever version is detected on Travis is packaged. Not sure how we would solve this.

**Comment by astorije** [comment]
Listing random ideas, see if that gets us anywhere.

- I know very little about building debs, is there a way to tell whatever needs it that it requires `sqlite` from apt as well? Something like adding `sqlite` to [`control`](https://github.com/thelounge/thelounge-deb/blob/master/debian/control#L6).

- We could use [`better-sqlite3`](https://www.npmjs.com/package/better-sqlite3) which may solve our issue. Again, I'm not sure exactly what's going on here, and looking closer it might not solve it.

- We could go for what seems to be called an "embedded JS database" like https://github.com/louischatriot/nedb which is more JS native so we wouldn't hit this. Definitely a more out-there idea, but I don't know, divergent thinking phase right now.

**Comment by astorije** [comment]
@SinZ163, we gave a shot at a fix in v3.0.0-pre.6 deb. Would you mind testing it? It's at https://github.com/thelounge/thelounge/releases/download/v3.0.0-pre.6/thelounge_3.0.0-pre.6-1_all.deb

**Comment by Zarthus** [comment]
@astorije I just ran it in a debian buster docker container and it seems to work, but I have no experience with debian packaging once it's on apt.

**Comment by SinZ163** [comment]
@astorije It now just errors out that sqlite3 hasn't been installed.

```
Preparing to unpack thelounge_3.0.0-pre.6-1_all.deb ...
Unpacking thelounge (3.0.0-pre.6-1) over (3.0.0-pre.5-1) ...
dpkg: dependency problems prevent configuration of thelounge:
 thelounge depends on sqlite3; however:
  Package sqlite3 is not installed.

dpkg: error processing package thelounge (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 thelounge
```

**Comment by Zarthus** [comment]
@SinZ163 I installed it with `sudo apt install ./thelounge_3.0.0-pre.6-1_all.deb` rather than `dpkg -i`, which properly installs both sqlite3 and nodejs

**Comment by SinZ163** [comment]
Oh you can do that?! TIL

the documentation in this repo only ever mentioned dpkg -i

**Comment by xPaw** [comment]
Okay installing sqlite via apt doesn't solve the problem.

I think what we should do is ship node binary in the debian packge.

1. We control Node version we ship for Lounge
2. Node is no longer required to be installed via apt
3. We provide correct sqlite binding for the node version we ship

It shouldn't be too hard to do as Node is just a single binary we can drop in.

**Comment by astorije** [comment]
> I think what we should do is ship node binary in the debian packge.

That's quite a clever idea, but I'll admit it's the first time I hear about this (it's not impossible some software I use does this, but because it's abstracted away, I wouldn't realize).
Besides TL, I don't run many Node projects, but I do have a few Python ones and they all use the host version of Python.
What drawbacks could this bring (besides the slight size increase, nbd)?

The solution feels somewhat disproportionate compared to the problem (I do appreciate the other benefits, but just weighing options at the moment), is there a way we could embed something closer to SQLite (binary, bindings, etc.) since it's the culprit in this situation?

Alternatively, have you given a thought about https://github.com/WebReflection/dblite? It seems like it would solve the issue more generically, so that other platforms (Arch?) would benefit from this too.

**Comment by xPaw** [comment]
I have definitely seen other software bundle the runtime (even Electron probably does).

> The solution feels somewhat disproportionate compared to the problem

**Comment by xPaw** [comment]
> Also, mind explaining why your PR fixes this issue? I'm failing to understand why precisely.

Because it packages the exact node binary version that is used by the sqlite bindings.

So it goes like this: Travis downloads latest Node v8, installs Lounge (and sqlite bindings), then copies this same Node version to the package.

**Comment by astorije** [comment]
@xPaw (just spitballing here, don't hit me 🙂), do you think could TL be installed and work as expected if `node-sqlite3` was installed as via `postinst` instead?

It's probably a very silly idea, but if there is a way to (1) make [this step](https://github.com/thelounge/thelounge-deb/blob/master/build-package#L16) not install `node-sqlite3` and (2) let `postinst` install `node-sqlite3`, I'm wondering if that wouldn't solve the binding issue.

(1) could be done (in build script) either by:
- gross: download the tarball of the version of TL to install, untar, tamper with its `package.json` to remove `node-sqlite3` then proceeding with `npm install -g thelounge@...` as before
- less gross (?): moving `node-sqlite3` to [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies) (which is possible since your PR https://github.com/thelounge/thelounge/pull/2391/files, and maybe even desired either way!) then changing the build script to use `npm install -g --no-optional thelounge@...`

(2) would be a "simple" `npm install sqlite3` in the correct directory in `postinst` step or something

That would make things closer to the situation people are encountering with the regular npm package and they have to install `sqlite3` manually... no?

Alright, I feel like I'm blinded by the possibility here as I don't see why it wouldn't work, but I'm so expecting you to stop me right at the very start because of something stupid I missed :D

**Comment by astorije** [comment]
> That's another option, yeah. 

Hey, it looks like #33 is going well, so far...

> However if node updates on host, then the installed sqlite version will mismatch and will require a reinstall as well.

That would be the case when installed from source or npm release though, correct?
Even if not, if that's the price for having a .deb that actually works on RPis and others, that's really a small price to pay! :) Upgrading Node is not something you do every day anyway.

> The only reason they have to do that is poor npm defaults with global installs. So they have to force root permissions if you they install as root.

Yeah, and I had to use `--unsafe-perm` in #33 as well, because sqlite3 has to be installed globally and with `sudo`.

**Comment by astorije** [comment]
@SinZ163, could you test the pre.7 deb and see if it works ok for you? 🙏
